server:
  port: 8080

spring:
  application:
    name: blog-be
  datasource:
    url: jdbc:postgresql://localhost:5432/blog-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

